version: "3.3"
services:
    database:
        image: postgres:12-alpine
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: user
            POSTGRES_PASSWORD: secret
            POSTGRES_DB: db
